-- MySQL Script generated by MySQL Workbench
-- Fri Oct 12 16:52:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema idiomas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema idiomas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `idiomas` DEFAULT CHARACTER SET utf8 ;
USE `idiomas` ;

-- -----------------------------------------------------
-- Table `idiomas`.`auth_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`auth_group` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`auth_group` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`django_content_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`django_content_type` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`django_content_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `app_label` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `django_content_type_app_label_model_76bd3d3b_uniq` (`app_label` ASC, `model` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`auth_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`auth_permission` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`auth_permission` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `content_type_id` INT(11) NOT NULL,
  `codename` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_permission_content_type_id_codename_01ab375a_uniq` (`content_type_id` ASC, `codename` ASC),
  CONSTRAINT `auth_permission_content_type_id_2f476e4b_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `idiomas`.`django_content_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`auth_group_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`auth_group_permissions` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`auth_group_permissions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `group_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_group_permissions_group_id_permission_id_0cd325b0_uniq` (`group_id` ASC, `permission_id` ASC),
  INDEX `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm` (`permission_id` ASC),
  CONSTRAINT `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `idiomas`.`auth_permission` (`id`),
  CONSTRAINT `auth_group_permissions_group_id_b120cbf9_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `idiomas`.`auth_group` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`auth_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`auth_user` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`auth_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(128) NOT NULL,
  `last_login` DATETIME(6) NULL DEFAULT NULL,
  `is_superuser` TINYINT(1) NOT NULL,
  `username` VARCHAR(150) NOT NULL,
  `first_name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `is_staff` TINYINT(1) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `date_joined` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`auth_user_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`auth_user_groups` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`auth_user_groups` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `group_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_groups_user_id_group_id_94350c0c_uniq` (`user_id` ASC, `group_id` ASC),
  INDEX `auth_user_groups_group_id_97559544_fk_auth_group_id` (`group_id` ASC),
  CONSTRAINT `auth_user_groups_group_id_97559544_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `idiomas`.`auth_group` (`id`),
  CONSTRAINT `auth_user_groups_user_id_6a12ed8b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `idiomas`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`auth_user_user_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`auth_user_user_permissions` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`auth_user_user_permissions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_user_permissions_user_id_permission_id_14a6b632_uniq` (`user_id` ASC, `permission_id` ASC),
  INDEX `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm` (`permission_id` ASC),
  CONSTRAINT `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `idiomas`.`auth_permission` (`id`),
  CONSTRAINT `auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `idiomas`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`pais` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`pais` (
  `id_pais` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `alias` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id_pais`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`ciudad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`ciudad` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`ciudad` (
  `id_ciudad` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_id_pais` INT(11) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `alias` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id_ciudad`),
  INDEX `fk_pais1_idx` (`fk_id_pais` ASC),
  CONSTRAINT `fk_pais1`
    FOREIGN KEY (`fk_id_pais`)
    REFERENCES `idiomas`.`pais` (`id_pais`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`oferta_academica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`oferta_academica` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`oferta_academica` (
  `id_oferta_academica` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_oferta_academica`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`escala_notas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`escala_notas` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`escala_notas` (
  `id_escala_notas` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `nota_minima` FLOAT NOT NULL,
  `nota_maxima` FLOAT NOT NULL,
  `nota_aprobatoria` FLOAT NOT NULL,
  `decimales` INT(11) NOT NULL DEFAULT '2',
  PRIMARY KEY (`id_escala_notas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`idioma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`idioma` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`idioma` (
  `id_idioma` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `etiqueta` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id_idioma`),
  UNIQUE INDEX `id_idioma_UNIQUE` (`id_idioma` ASC),
  UNIQUE INDEX `etiqueta_UNIQUE` (`etiqueta` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`programa_academico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`programa_academico` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`programa_academico` (
  `id_programa_academico` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_id_escala_notas` INT(11) NOT NULL,
  `fk_id_idioma` INT(11) NOT NULL,
  PRIMARY KEY (`id_programa_academico`),
  INDEX `fk_escala_notas1_idx` (`fk_id_escala_notas` ASC),
  INDEX `fk_idioma1_idx` (`fk_id_idioma` ASC),
  CONSTRAINT `fk_escala_notas1`
    FOREIGN KEY (`fk_id_escala_notas`)
    REFERENCES `idiomas`.`escala_notas` (`id_escala_notas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idioma1`
    FOREIGN KEY (`fk_id_idioma`)
    REFERENCES `idiomas`.`idioma` (`id_idioma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`contenido_nivel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`contenido_nivel` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`contenido_nivel` (
  `id_contenido_nivel` INT(11) NOT NULL,
  `contenido` VARCHAR(45) NOT NULL,
  `version` INT NOT NULL,
  PRIMARY KEY (`id_contenido_nivel`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`nivel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`nivel` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`nivel` (
  `id_nivel` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_id_programa_academico` INT(11) NOT NULL,
  `fk_id_contenido_nivel` INT(11) NOT NULL,
  PRIMARY KEY (`id_nivel`),
  INDEX `fk_programa_academico1_idx` (`fk_id_programa_academico` ASC),
  INDEX `fk_contenido_nivel1_idx` (`fk_id_contenido_nivel` ASC),
  CONSTRAINT `fk_programa_academico1`
    FOREIGN KEY (`fk_id_programa_academico`)
    REFERENCES `idiomas`.`programa_academico` (`id_programa_academico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contenido_nivel1`
    FOREIGN KEY (`fk_id_contenido_nivel`)
    REFERENCES `idiomas`.`contenido_nivel` (`id_contenido_nivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`curso` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`curso` (
  `id_curso` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_id_oferta_academica` INT(11) NOT NULL,
  `fk_id_nivel` INT(11) NOT NULL,
  `cupo` INT NOT NULL,
  PRIMARY KEY (`id_curso`),
  INDEX `fk_oferta_academica1_idx` (`fk_id_oferta_academica` ASC),
  INDEX `fk_nivel1_idx` (`fk_id_nivel` ASC),
  CONSTRAINT `fk_oferta_academica1`
    FOREIGN KEY (`fk_id_oferta_academica`)
    REFERENCES `idiomas`.`oferta_academica` (`id_oferta_academica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nivel1`
    FOREIGN KEY (`fk_id_nivel`)
    REFERENCES `idiomas`.`nivel` (`id_nivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`conjunto_notas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`conjunto_notas` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`conjunto_notas` (
  `id_conjunto_notas` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_id_curso` INT(11) NOT NULL,
  PRIMARY KEY (`id_conjunto_notas`),
  INDEX `fk_curso2_idx` (`fk_id_curso` ASC),
  CONSTRAINT `fk_curso2`
    FOREIGN KEY (`fk_id_curso`)
    REFERENCES `idiomas`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`descuento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`descuento` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`descuento` (
  `id_descuento` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_descuento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`django_admin_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`django_admin_log` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`django_admin_log` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `action_time` DATETIME(6) NOT NULL,
  `object_id` LONGTEXT NULL DEFAULT NULL,
  `object_repr` VARCHAR(200) NOT NULL,
  `action_flag` SMALLINT(5) UNSIGNED NOT NULL,
  `change_message` LONGTEXT NOT NULL,
  `content_type_id` INT(11) NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `django_admin_log_content_type_id_c4bce8eb_fk_django_co` (`content_type_id` ASC),
  INDEX `django_admin_log_user_id_c564eba6_fk_auth_user_id` (`user_id` ASC),
  CONSTRAINT `django_admin_log_content_type_id_c4bce8eb_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `idiomas`.`django_content_type` (`id`),
  CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `idiomas`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`django_migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`django_migrations` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`django_migrations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `app` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `applied` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`django_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`django_session` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`django_session` (
  `session_key` VARCHAR(40) NOT NULL,
  `session_data` LONGTEXT NOT NULL,
  `expire_date` DATETIME(6) NOT NULL,
  PRIMARY KEY (`session_key`),
  INDEX `django_session_expire_date_a5c62663` (`expire_date` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`tipo_documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`tipo_documento` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`tipo_documento` (
  `id_tipo_documento` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_tipo_documento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`documento` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`documento` (
  `id_documento` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_id_tipo_documento` INT(11) NOT NULL,
  `numero_documento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_documento`),
  INDEX `fk_tipo_documento1_idx` (`fk_id_tipo_documento` ASC),
  CONSTRAINT `fk_tipo_documento1`
    FOREIGN KEY (`fk_id_tipo_documento`)
    REFERENCES `idiomas`.`tipo_documento` (`id_tipo_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`examen_clasificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`examen_clasificacion` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`examen_clasificacion` (
  `id_examen_clasificacion` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_examen_clasificacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`genero_sexual`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`genero_sexual` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`genero_sexual` (
  `id_genero_sexual` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `alias` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id_genero_sexual`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`horario` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`horario` (
  `id_horario` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_horario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`inscrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`inscrito` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`inscrito` (
  `id_inscrito` INT NOT NULL AUTO_INCREMENT,
  `fk_id_tipo_documento` INT(11) NOT NULL,
  `fk_id_genero_sexual` INT(11) NOT NULL,
  `fk_auth_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id_inscrito`),
  INDEX `fk_tipo_documento3_idx` (`fk_id_tipo_documento` ASC),
  INDEX `fk_genero_sexual1_idx` (`fk_id_genero_sexual` ASC),
  INDEX `fk_auth_user1_idx` (`fk_auth_user_id` ASC),
  CONSTRAINT `fk_tipo_documento3`
    FOREIGN KEY (`fk_id_tipo_documento`)
    REFERENCES `idiomas`.`tipo_documento` (`id_tipo_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_genero_sexual1`
    FOREIGN KEY (`fk_id_genero_sexual`)
    REFERENCES `idiomas`.`genero_sexual` (`id_genero_sexual`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auth_user1`
    FOREIGN KEY (`fk_auth_user_id`)
    REFERENCES `idiomas`.`auth_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idiomas`.`estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`estudiante` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`estudiante` (
  `id_estudiante` INT NOT NULL AUTO_INCREMENT,
  `fk_id_inscrito` INT NOT NULL,
  PRIMARY KEY (`id_estudiante`),
  INDEX `fk_inscrito1_idx` (`fk_id_inscrito` ASC),
  CONSTRAINT `fk_inscrito1`
    FOREIGN KEY (`fk_id_inscrito`)
    REFERENCES `idiomas`.`inscrito` (`id_inscrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idiomas`.`usuarioMatriculadoenCurso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`usuarioMatriculadoenCurso` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`usuarioMatriculadoenCurso` (
  `id_usuarioMatriculadoenCursocol` INT NOT NULL AUTO_INCREMENT,
  `fk_id_estudiante` INT NOT NULL,
  `fk_id_curso` INT(11) NOT NULL,
  PRIMARY KEY (`id_usuarioMatriculadoenCursocol`),
  INDEX `fk_estudiante1_idx` (`fk_id_estudiante` ASC),
  INDEX `fk_curso3_idx` (`fk_id_curso` ASC),
  CONSTRAINT `fk_curso3`
    FOREIGN KEY (`fk_id_curso`)
    REFERENCES `idiomas`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante1`
    FOREIGN KEY (`fk_id_estudiante`)
    REFERENCES `idiomas`.`estudiante` (`id_estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`nota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`nota` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`nota` (
  `id_nota` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_id_usuarioMatriculadoenCursocol` INT NOT NULL,
  `nota` FLOAT NOT NULL,
  `fk_id_conjunto_notas` INT(11) NOT NULL,
  PRIMARY KEY (`id_nota`),
  INDEX `fk_usuarioMatriculadoenCurso1_idx` (`fk_id_usuarioMatriculadoenCursocol` ASC),
  INDEX `fk_conjunto_notas1_idx` (`fk_id_conjunto_notas` ASC),
  CONSTRAINT `fk_usuarioMatriculadoenCurso1`
    FOREIGN KEY (`fk_id_usuarioMatriculadoenCursocol`)
    REFERENCES `idiomas`.`usuarioMatriculadoenCurso` (`id_usuarioMatriculadoenCursocol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conjunto_notas1`
    FOREIGN KEY (`fk_id_conjunto_notas`)
    REFERENCES `idiomas`.`conjunto_notas` (`id_conjunto_notas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`periodicidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`periodicidad` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`periodicidad` (
  `id_periodicidad` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `meses` INT(11) NOT NULL,
  PRIMARY KEY (`id_periodicidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`periodo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`periodo` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`periodo` (
  `id_periodo` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_periodo_anterior` INT(11) NULL DEFAULT NULL,
  `fk_id_periodicidad` INT(11) NOT NULL,
  `alias` VARCHAR(45) NOT NULL,
  `secuencia` VARCHAR(45) NOT NULL DEFAULT '1',
  `anio` INT(11) NULL DEFAULT NULL,
  `estado` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_periodo`),
  INDEX `fk_periodo1_idx` (`fk_periodo_anterior` ASC),
  INDEX `fk_periodicidad1_idx` (`fk_id_periodicidad` ASC),
  CONSTRAINT `fk_periodo1`
    FOREIGN KEY (`fk_periodo_anterior`)
    REFERENCES `idiomas`.`periodo` (`id_periodo`),
  CONSTRAINT `fk_periodicidad1`
    FOREIGN KEY (`fk_id_periodicidad`)
    REFERENCES `idiomas`.`periodicidad` (`id_periodicidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`cursos_horarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`cursos_horarios` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`cursos_horarios` (
  `fk_id_curso` INT(11) NOT NULL,
  `fk_id_horario` INT(11) NOT NULL,
  PRIMARY KEY (`fk_id_curso`, `fk_id_horario`),
  INDEX `fk_horario1_idx` (`fk_id_horario` ASC),
  INDEX `fk_curso1_idx` (`fk_id_curso` ASC),
  CONSTRAINT `fk_curso1`
    FOREIGN KEY (`fk_id_curso`)
    REFERENCES `idiomas`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_horario1`
    FOREIGN KEY (`fk_id_horario`)
    REFERENCES `idiomas`.`horario` (`id_horario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `idiomas`.`preinscipcion_curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`preinscipcion_curso` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`preinscipcion_curso` (
  `id_preinscipcion_curso` INT NOT NULL,
  `fk_id_descuento` INT(11) NOT NULL,
  PRIMARY KEY (`id_preinscipcion_curso`),
  INDEX `fk_descuento1_idx` (`fk_id_descuento` ASC),
  CONSTRAINT `fk_descuento1`
    FOREIGN KEY (`fk_id_descuento`)
    REFERENCES `idiomas`.`descuento` (`id_descuento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idiomas`.`preinscripcion_clasificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`preinscripcion_clasificacion` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`preinscripcion_clasificacion` (
  `id_preinscripcion_clasificacion` INT NOT NULL,
  `fk_id_descuento` INT(11) NOT NULL,
  PRIMARY KEY (`id_preinscripcion_clasificacion`),
  INDEX `fk_descuento2_idx` (`fk_id_descuento` ASC),
  CONSTRAINT `fk_descuento2`
    FOREIGN KEY (`fk_id_descuento`)
    REFERENCES `idiomas`.`descuento` (`id_descuento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idiomas`.`calendario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`calendario` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`calendario` (
  `id_calendario` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `calendariocol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_calendario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idiomas`.`tipo_evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`tipo_evento` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`tipo_evento` (
  `id_tipo_evento` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_tipo_evento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idiomas`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`evento` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`evento` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `fk_id_tipo_evento` INT NOT NULL,
  PRIMARY KEY (`id_evento`),
  INDEX `fk_tipo_evento1_idx` (`fk_id_tipo_evento` ASC),
  CONSTRAINT `fk_tipo_evento1`
    FOREIGN KEY (`fk_id_tipo_evento`)
    REFERENCES `idiomas`.`tipo_evento` (`id_tipo_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idiomas`.`preinscrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`preinscrito` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`preinscrito` (
  `id_preinscrito` INT NOT NULL AUTO_INCREMENT,
  `fk_id_tipo_documento` INT(11) NOT NULL,
  `fk_id_genero_sexual` INT(11) NOT NULL,
  PRIMARY KEY (`id_preinscrito`),
  INDEX `fk_tipo_documento2_idx` (`fk_id_tipo_documento` ASC),
  INDEX `fk_genero_sexual2_idx` (`fk_id_genero_sexual` ASC),
  CONSTRAINT `fk_tipo_documento2`
    FOREIGN KEY (`fk_id_tipo_documento`)
    REFERENCES `idiomas`.`tipo_documento` (`id_tipo_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_genero_sexual2`
    FOREIGN KEY (`fk_id_genero_sexual`)
    REFERENCES `idiomas`.`genero_sexual` (`id_genero_sexual`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `idiomas`.`calificaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `idiomas`.`calificaciones` ;

CREATE TABLE IF NOT EXISTS `idiomas`.`calificaciones` (
  `id_calificaciones` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_calificaciones`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
