from .adminForms import *
from .contenidoNivelForms import *
from .userForms import *
from .auth import *
from .profile import *
from .examenClasificacionForms import *
from .periodoForm import *
from .PersonaAdministracionForm import *
from .franjaForms import *
from .conjuntoNotasForm import *
from .grupoForms import *
from .aplazarForm import *
from .ofertaForms import *
from .encuestaForms import *
from .devolucionForms import *
from .DescuentoAplicadoForm import *
from .DescuentoSolicitadoForm import *