"""
Django settings for djsialex project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

from django.utils.translation import ugettext_lazy as _

"""from sshtunnel import SSHTunnelForwarder

# Connect to a server using the ssh keys. See the sshtunnel documentation for using password authentication
ssh_tunnel = SSHTunnelForwarder(
    ('168.176.18.15', 33000),
    ssh_username='extdevelop',
    ssh_password="2022/IDuque",
    remote_bind_address=('localhost', 5432),
)
ssh_tunnel.start()"""


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-plag545x0!5y9&v7jclhy@o!&ekam7_!lt38736c8-e84c(34'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
""" # Prod
DEBUG = False 
"""
ALLOWED_HOSTS = [
    '168.176.18.33',
    '127.0.0.1',
    'localhost',
    '168.176.84.35',
    '168.176.18.15',
    'http://www.extensionidiomas.unal.edu.co',
    'www.extensionidiomas.unal.edu.co',
    'extensionidiomas.unal.edu.co',
    '3.89.102.66',
    'ec2-3-89-102-66.compute-1.amazonaws.com'

]
DJANGO_EASY_AUDIT_WATCH_REQUEST_EVENTS = False


# Application definition

INSTALLED_APPS = [
    'administracion.apps.AdministracionConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    #'jquery',
    'django.contrib.admin',
    'widget_tweaks',
    'bootstrap3',
    'captcha',
    'bootstrap_datepicker_plus',
    'bootstrap_modal_forms',
    'auditlog',
    'explorer',
    'bootstrapform',
    'ckeditor'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',    
    'django.middleware.common.CommonMiddleware',
    'djsialex.middleware.middleware.FilterLoginMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
]

MIDDLEWARE_CLASSES = [
    'auditlog.middleware.AuditlogMiddleware',
]


ROOT_URLCONF = 'djsialex.urls'

TEMPLATES = [
    {
        'APP_DIRS': False,
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/'), r'templates/'],
        'OPTIONS': {
            'context_processors': [
                'administracion.processors.evento_permiso',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries':{
                'profile_tags': 'administracion.templatetags.profile_tags',
            },
            'loaders': [
                (
                    'django.template.loaders.cached.Loader',
                    [
                        'django.template.loaders.filesystem.Loader',
                        'django.template.loaders.app_directories.Loader',
                    ]
                ),
            ],
        },
    },
]


WSGI_APPLICATION = 'djsialex.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
#}

"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sialex',
        'USER': 'sialex',
        'PASSWORD': 'sialex',
        'HOST': 'localhost',
        'PORT': '5432',
    },
}
"""
# dev
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sialex',
        'USER': 'sialex',
        'PASSWORD': 'adminsialex',
        'HOST': 'database-1-slx.co1rl716txsf.us-east-1.rds.amazonaws.com',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/
LANGUAGE_CODE = 'es'

LANGUAGES = (
    ('en', _('English')),
    ('es', _('Spanish')),
)

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)


TIME_ZONE = 'UTC'
""" #dev
TIME_ZONE = 'America/Bogota'
"""

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR+"/../static_deployed/"

LOGIN_REDIRECT_URL = '/administracion'

LOGOUT_REDIRECT_URL = '/'

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')

MAX_IMAGE_SIZE = '20971520'

CAPTCHA_FONT_SIZE = 40;

CAPTCHA_BACKGROUND_COLOR = '#ffffff'

SESSION_COOKIE_AGE = 1*60
MAX_IMAGE_SIZE = '20971520'

SESSION_COOKIE_AGE = 60*60

""" # prod
EMAIL_HOST = 'smtp-relay.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'sialex_fchbog@unal.edu.co'
EMAIL_HOST_PASSWORD = 'Unal2021'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'sialex_fchbog@unal.edu.co'
"""

EMAIL_HOST = 'smtp-relay.sendinblue.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'iaduquea@unal.edu.co'
EMAIL_HOST_PASSWORD = '4z0aWsSwUVKj3bqt'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
DEFAULT_FROM_EMA ='sialex_fchbog@unal.edu.co'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'

LOGIN_URL = '/acceso/login'

EXPLORER_CONNECTIONS = {'Default': 'default'}
EXPLORER_DEFAULT_CONNECTION = 'default'

CHOICES_SEPARATOR = ","

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source']
        ],
        'width': '100%'
    },
}
